### ISSUE TITLE
Using displayname instead of username and tag (data leak)

### ISSUE THREAD

**Issue by mtorials** [byNoobiYT/issue-manager-issues#1]
I think it is better to use the displayname in the topic of the issue. You could also use the username but without tag. With the tag everyone knows your discord "address". I don not want to be PMed all the time...

**Comment by byNoobiYT** [comment]
Yea, i'll agree with that.

**Comment by mtorials** [comment]
Can we close this issue or is this intentionally left open?

**Comment by byNoobiYT** [comment]
Haven't made any changes to the bot. I'll close the issue when it's resolved.

**Comment by byNoobiYT** [comment]
Changes had been made and new version has been deployed successfully. Thanks for your contribution!
